name: firecrawl
services:
  playwright-service:
    build: ./apps/playwright-service-ts
    environment:
      - PORT=3000
      - BLOCK_MEDIA=true
    networks:
      - backend

  firecrawl-api:
    build:
      context: ./apps/api
      args:
        - COREPACK_INTEGRITY_KEYS=0
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_RATE_LIMIT_URL=redis://redis:6379
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3000
      - PORT=3002
      - HOST=0.0.0.0
      - BULL_AUTH_KEY=markeye_secret_key
      - USE_DB_AUTHENTICATION=false
      - COREPACK_INTEGRITY_KEYS=0
    depends_on:
      - redis
      - playwright-service
    ports:
      - "3002:3002"
    networks:
      - backend

  worker:
    build:
      context: ./apps/api
      args:
        - COREPACK_INTEGRITY_KEYS=0
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_RATE_LIMIT_URL=redis://redis:6379
      - PLAYWRIGHT_MICROSERVICE_URL=http://playwright-service:3000
      - PORT=3002
      - HOST=0.0.0.0
      - BULL_AUTH_KEY=markeye_secret_key
      - USE_DB_AUTHENTICATION=false
      - COREPACK_INTEGRITY_KEYS=0
    depends_on:
      - redis
      - playwright-service
      - firecrawl-api
    command: ["pnpm", "run", "workers"]
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

networks:
  backend:
    driver: bridge
